main().catch(console.error)

async function main() {
  console.log('running worker')
}
